# MT5 order type constants (mirror MetaTrader5 enums)
ORDER_TYPE_BUY = 0
ORDER_TYPE_SELL = 1
ORDER_TYPE_BUY_LIMIT = 2
ORDER_TYPE_SELL_LIMIT = 3
ORDER_TYPE_BUY_STOP = 4
ORDER_TYPE_SELL_STOP = 5

ORDER_TYPE_NAMES = {
    ORDER_TYPE_BUY: "BUY",
    ORDER_TYPE_SELL: "SELL",
    ORDER_TYPE_BUY_LIMIT: "BUY_LIMIT",
    ORDER_TYPE_SELL_LIMIT: "SELL_LIMIT",
    ORDER_TYPE_BUY_STOP: "BUY_STOP",
    ORDER_TYPE_SELL_STOP: "SELL_STOP",
}

# Trade actions
TRADE_ACTION_DEAL = 1       # Market order
TRADE_ACTION_PENDING = 5    # Pending order
TRADE_ACTION_REMOVE = 8     # Remove pending order

# Trade return codes
TRADE_RETCODE_DONE = 10009
TRADE_RETCODE_PLACED = 10008

# Timeframe constants
TIMEFRAME_M1 = 1
TIMEFRAME_M5 = 5
TIMEFRAME_M15 = 15
TIMEFRAME_M30 = 30
TIMEFRAME_H1 = 16385
TIMEFRAME_H4 = 16388
TIMEFRAME_D1 = 16408

TIMEFRAME_MAP = {
    "M1": TIMEFRAME_M1,
    "M5": TIMEFRAME_M5,
    "M15": TIMEFRAME_M15,
    "M30": TIMEFRAME_M30,
    "H1": TIMEFRAME_H1,
    "H4": TIMEFRAME_H4,
    "D1": TIMEFRAME_D1,
}

# Position type
POSITION_TYPE_BUY = 0
POSITION_TYPE_SELL = 1

# Order filling
ORDER_FILLING_FOK = 0
ORDER_FILLING_IOC = 1
ORDER_FILLING_RETURN = 2

# Order time
ORDER_TIME_GTC = 0
